# Generated by Django 2.1.2 on 2018-12-08 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20181207_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
