# Generated by Django 2.1.2 on 2018-12-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendrequest_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='time',
        ),
    ]
