# Generated by Django 2.1.2 on 2019-01-06 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20190104_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionmessage',
            name='discussion_id',
        ),
        migrations.RemoveField(
            model_name='discussionmessage',
            name='message_sender',
        ),
        migrations.RemoveField(
            model_name='discussionusers',
            name='discussion_id',
        ),
        migrations.RemoveField(
            model_name='discussionusers',
            name='discussion_user',
        ),
        migrations.AddField(
            model_name='creatediscussion',
            name='discussion_time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DiscussionMessage',
        ),
        migrations.DeleteModel(
            name='DiscussionUsers',
        ),
    ]
