# Generated by Django 2.1.2 on 2019-01-11 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussionmessage_discussionusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
