# Generated by Django 2.1.2 on 2018-12-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181129_0402'),
        ('user', '0003_auto_20181201_1403'),
    ]

    operations = [
    ]
